source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "active_model_serializers"

gem "bootsnap", require: false

gem "config"

gem "devise"

gem "devise-i18n"

gem "devise_token_auth"

gem "kaminari"

gem "mysql2", "~> 0.5"

gem "puma", "~> 5.0"

gem "rack-cors"

gem "rails", "~> 7.0.8"

gem "rails-i18n"

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "factory_bot_rails"
  gem "faker"
  gem "letter_opener_web"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
