source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "bootsnap", require: false

gem "mysql2", "~> 0.5"

gem "puma", "~> 5.0"

gem "rails", "~> 7.0.8"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
end
