AllCops:
  Exclude: 
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/**"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Layout/ClassStructure: 
  Enabled: true 

Layout/DotPosition:
  EnforcedStyle: trailing 

Layout/EmptyLinesAroundAttributeAccessor: 
  Enabled: true

Layout/ExtraSpacing: 
  Exclude: 
    - "db/migrate/*.rb"

Layout/FirstArrayElementIndentation: 
  EnforcedStyle: consistent 

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent 

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods 

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver 

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false 

Layout/SpaceAroundMethodCallOperator: 
  Enabled: true