AllCops:
  Exclude: 
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/**"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Layout/ClassStructure: 
  Enabled: true 

Layout/DotPosition:
  EnforcedStyle: trailing 

Layout/EmptyLinesAroundAttributeAccessor: 
  Enabled: true